/* Samara AI Assistant — public website, no patient/ERP access. */
(function(){
'use strict';
var CFG=window.SAMARA_SITE_CONFIG||{};
var L={
 en:{name:'English',locale:'en-IN',hello:'Hello! I am Samara AI. You can type or speak. I can show our rooms, gallery and opening video, or help you make an enquiry.',ph:'Ask Samara…',rooms:'Show rooms',gallery:'Gallery',video:'Video',enquiry:'Enquiry',listen:'Listening…',noVoice:'Voice input is not supported by this browser. Please type your question.',fallback:'I can help with Samara Assisted Living, rooms, gallery, video and enquiries. For detailed questions, our secure AI service will be enabled next.'},
 ta:{name:'தமிழ்',locale:'ta-IN',hello:'வணக்கம்! நான் Samara AI. நீங்கள் தமிழில் பேசலாம் அல்லது தட்டச்சு செய்யலாம். அறைகள், கேலரி, வீடியோ மற்றும் விசாரணைக்கு உதவுகிறேன்.',ph:'Samara-விடம் கேளுங்கள்…',rooms:'அறைகள்',gallery:'கேலரி',video:'வீடியோ',enquiry:'விசாரணை',listen:'கேட்கிறேன்…',noVoice:'இந்த உலாவியில் குரல் உள்ளீடு கிடைக்கவில்லை. தயவுசெய்து தட்டச்சு செய்யவும்.',fallback:'Samara Assisted Living பற்றிய தகவல், அறைகள், கேலரி, வீடியோ மற்றும் விசாரணைக்கு நான் உதவ முடியும்.'},
 te:{name:'తెలుగు',locale:'te-IN',hello:'నమస్కారం! నేను Samara AI. మీరు తెలుగులో మాట్లాడవచ్చు లేదా టైప్ చేయవచ్చు. గదులు, గ్యాలరీ, వీడియో మరియు విచారణలో సహాయం చేస్తాను.',ph:'Samaraని అడగండి…',rooms:'గదులు',gallery:'గ్యాలరీ',video:'వీడియో',enquiry:'విచారణ',listen:'వింటున్నాను…',noVoice:'ఈ బ్రౌజర్‌లో వాయిస్ ఇన్‌పుట్ అందుబాటులో లేదు. దయచేసి టైప్ చేయండి.',fallback:'Samara Assisted Living, గదులు, గ్యాలరీ, వీడియో మరియు విచారణ గురించి నేను సహాయం చేయగలను.'},
 hi:{name:'हिन्दी',locale:'hi-IN',hello:'नमस्ते! मैं Samara AI हूँ। आप हिन्दी में बोल या टाइप कर सकते हैं। मैं कमरे, गैलरी, वीडियो और पूछताछ में मदद कर सकता हूँ।',ph:'Samara से पूछें…',rooms:'कमरे',gallery:'गैलरी',video:'वीडियो',enquiry:'पूछताछ',listen:'सुन रहा हूँ…',noVoice:'इस ब्राउज़र में वॉइस इनपुट उपलब्ध नहीं है। कृपया टाइप करें।',fallback:'मैं Samara Assisted Living, कमरे, गैलरी, वीडियो और पूछताछ के बारे में मदद कर सकता हूँ।'},
 kn:{name:'ಕನ್ನಡ',locale:'kn-IN',hello:'ನಮಸ್ಕಾರ! ನಾನು Samara AI. ನೀವು ಕನ್ನಡದಲ್ಲಿ ಮಾತನಾಡಬಹುದು ಅಥವಾ ಟೈಪ್ ಮಾಡಬಹುದು. ಕೊಠಡಿಗಳು, ಗ್ಯಾಲರಿ, ವೀಡಿಯೊ ಮತ್ತು ವಿಚಾರಣೆಗೆ ಸಹಾಯ ಮಾಡುತ್ತೇನೆ.',ph:'Samaraಗೆ ಕೇಳಿ…',rooms:'ಕೊಠಡಿಗಳು',gallery:'ಗ್ಯಾಲರಿ',video:'ವೀಡಿಯೊ',enquiry:'ವಿಚಾರಣೆ',listen:'ಕೇಳುತ್ತಿದ್ದೇನೆ…',noVoice:'ಈ ಬ್ರೌಸರ್‌ನಲ್ಲಿ ಧ್ವನಿ ಇನ್‌ಪುಟ್ ಲಭ್ಯವಿಲ್ಲ. ದಯವಿಟ್ಟು ಟೈಪ್ ಮಾಡಿ.',fallback:'Samara Assisted Living, ಕೊಠಡಿಗಳು, ಗ್ಯಾಲರಿ, ವೀಡಿಯೊ ಮತ್ತು ವಿಚಾರಣೆಯ ಬಗ್ಗೆ ನಾನು ಸಹಾಯ ಮಾಡಬಹುದು.'}
};
var lang='en', opened=false;
function esc(s){var d=document.createElement('div');d.textContent=s;return d.innerHTML}
function ui(){var root=document.createElement('div');root.innerHTML='<button class="sai-launch" id="sai-launch" aria-label="Ask Samara AI"><span>✦</span><span>Ask Samara AI</span></button><section class="sai-panel" id="sai-panel" aria-label="Samara AI assistant"><div class="sai-head"><img src="assets/samara-mark.png" alt=""><div class="sai-title"><strong>Samara AI</strong><small>Voice • Text • Rooms • Gallery</small></div><button class="sai-close" id="sai-close" aria-label="Close">×</button></div><div class="sai-langs" id="sai-langs"></div><div class="sai-msgs" id="sai-msgs" aria-live="polite"></div><div class="sai-quick" id="sai-quick"></div><form class="sai-compose" id="sai-form"><button type="button" class="sai-mic" id="sai-mic" aria-label="Voice input">🎙</button><input id="sai-input" autocomplete="off"><button class="sai-send" aria-label="Send">➤</button></form><div class="sai-note">Voice recognition availability depends on your browser/device.</div></section>';document.body.appendChild(root);renderLangs();setLang('en');bind()}
function add(text,who){var d=document.createElement('div');d.className='sai-msg '+(who==='user'?'sai-user':'sai-bot');d.textContent=text;document.getElementById('sai-msgs').appendChild(d);scroll()}
function media(src,cap,video){var d=document.createElement('div');d.className='sai-msg sai-media';d.innerHTML=video?'<video controls playsinline poster="assets/photos/video-poster.jpg"><source src="'+src+'" type="video/mp4"></video><p>'+esc(cap)+'</p>':'<img src="'+src+'" alt="'+esc(cap)+'" loading="lazy"><p>'+esc(cap)+'</p>';document.getElementById('sai-msgs').appendChild(d);scroll()}
function scroll(){var m=document.getElementById('sai-msgs');m.scrollTop=m.scrollHeight}
function renderLangs(){var x=document.getElementById('sai-langs');Object.keys(L).forEach(function(k){var b=document.createElement('button');b.className='sai-lang';b.type='button';b.dataset.lang=k;b.textContent=L[k].name;b.onclick=function(){setLang(k)};x.appendChild(b)})}
function setLang(k){lang=L[k]?k:'en';document.querySelectorAll('.sai-lang').forEach(function(b){b.classList.toggle('active',b.dataset.lang===lang)});document.getElementById('sai-input').placeholder=L[lang].ph;var q=document.getElementById('sai-quick');q.innerHTML='';[['rooms','rooms'],['gallery','gallery'],['video','video'],['enquiry','enquiry']].forEach(function(a){var b=document.createElement('button');b.type='button';b.textContent=L[lang][a[0]];b.onclick=function(){intent(a[1],true)};q.appendChild(b)});if(opened)add(L[lang].hello,'bot')}
function showRooms(){media('assets/photos/care-room-single.webp','Private / single care room');media('assets/photos/care-room.webp','Care room at Samara');media('assets/photos/care-room-triple.webp','Triple-sharing care room')}
function showGallery(){['centre-building','reception','welcome-wall','care-team','ribbon-cutting','lamp-lighting'].forEach(function(n){media('assets/photos/'+n+'.webp','Samara Assisted Living')})}
function intent(text,quick){var raw=String(text||''),s=raw.toLowerCase();if(!quick)add(raw,'user');
 if(s==='rooms'||/room|rooms|single|triple|அறை|ரூம்|గది|గదులు|कमरा|कमरे|ಕೊಠಡಿ|ರೂಮ್/.test(s)){showRooms();return}
 if(s==='gallery'||/gallery|photo|photos|picture|கேலரி|பட|గ్యాలరీ|ఫోటో|गैलरी|फोटो|ಗ್ಯಾಲರಿ|ಫೋಟೋ/.test(s)){showGallery();return}
 if(s==='video'||/video|reel|வீடியோ|వీడియో|वीडियो|ವೀಡಿಯೊ/.test(s)){media('assets/video/samara-opening.mp4','Samara Assisted Living — opening video',true);return}
 if(s==='enquiry'||/enquir|admission|contact|விசாரணை|அட்மிஷன்|చేర్పు|पूछताछ|प्रवेश|ವಿಚಾರಣೆ|ದಾಖಲಾತಿ/.test(s)){add(lang==='en'?'Certainly. I will take you to our care enquiry form.':L[lang].fallback,'bot');setTimeout(function(){location.href='contact.html#enquiry'},650);return}
 askAI(raw)}
function askAI(q){if(!CFG.aiEndpoint){add(L[lang].fallback,'bot');return}fetch(CFG.aiEndpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:q,language:lang,page:location.pathname})}).then(function(r){if(!r.ok)throw 0;return r.json()}).then(function(x){add(x.reply||L[lang].fallback,'bot')}).catch(function(){add(L[lang].fallback,'bot')})}
function voice(){var SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){add(L[lang].noVoice,'bot');return}var r=new SR(),mic=document.getElementById('sai-mic');r.lang=L[lang].locale;r.interimResults=false;r.maxAlternatives=1;mic.classList.add('listening');mic.title=L[lang].listen;r.onresult=function(e){var t=e.results[0][0].transcript;document.getElementById('sai-input').value=t;intent(t,false)};r.onerror=function(){add(L[lang].noVoice,'bot')};r.onend=function(){mic.classList.remove('listening');mic.title=''};r.start()}
function bind(){var p=document.getElementById('sai-panel');document.getElementById('sai-launch').onclick=function(){p.classList.add('open');if(!opened){opened=true;add(L[lang].hello,'bot')}setTimeout(function(){document.getElementById('sai-input').focus()},50)};document.getElementById('sai-close').onclick=function(){p.classList.remove('open')};document.getElementById('sai-mic').onclick=voice;document.getElementById('sai-form').onsubmit=function(e){e.preventDefault();var i=document.getElementById('sai-input'),v=i.value.trim();if(v){i.value='';intent(v,false)}}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ui);else ui();
})();
