/* Samara AI Assistant — public website, no patient/ERP access. */
(function(){
'use strict';
var CFG=window.SAMARA_SITE_CONFIG||{};
var L={
 en:{name:'English',locale:'en-IN',hello:'Hello! I am Samara AI. You can type or speak. I can show our rooms, gallery and opening video, or help you make an enquiry.',ph:'Ask Samara…',rooms:'Show rooms',gallery:'Gallery',video:'Video',enquiry:'Enquiry',listen:'Listening…',noVoice:'Voice input is not supported by this browser. Please type your question.',fallback:'I can help with Samara Assisted Living, rooms, gallery, video and enquiries. For detailed questions, our secure AI service will be enabled next.'},
 ta:{name:'தமிழ்',locale:'ta-IN',hello:'வணக்கம்! நான் Samara AI. நீங்கள் தமிழில் பேசலாம் அல்லது தட்டச்சு செய்யலாம். அறைகள், கேலரி, வீடியோ மற்றும் விசாரணைக்கு உதவுகிறேன்.',ph:'Samara-விடம் கேளுங்கள்…',rooms:'அறைகள்',gallery:'கேலரி',video:'வீடியோ',enquiry:'விசாரணை',listen:'கேட்கிறேன்…',noVoice:'இந்த உலாவியில் குரல் உள்ளீடு கிடைக்கவில்லை. தயவுசெய்து தட்டச்சு செய்யவும்.',fallback:'Samara Assisted Living பற்றிய தகவல், அறைகள், கேலரி, வீடியோ மற்றும் விசாரணைக்கு நான் உதவ முடியும்.'},
 te:{name:'తెలుగు',locale:'te-IN',hello:'నమస్కారం! నేను Samara AI. మీరు తెలుగులో మాట్లాడవచ్చు లేదా టైప్ చేయవచ్చు. గదులు, గ్యాలరీ, వీడియో మరియు విచారణలో సహాయం చేస్తాను.',ph:'Samaraని అడగండి…',rooms:'గదులు',gallery:'గ్యాలరీ',video:'వీడియో',enquiry:'విచారణ',listen:'వింటున్నాను…',noVoice:'ఈ బ్రౌజర్‌లో వాయిస్ ఇన్‌పుట్ అందుబాటులో లేదు. దయచేసి టైప్ చేయండి.',fallback:'Samara Assisted Living, గదులు, గ్యాలరీ, వీడియో మరియు విచారణ గురించి నేను సహాయం చేయగలను.'},
 hi:{name:'हिन्दी',locale:'hi-IN',hello:'नमस्ते! मैं Samara AI हूँ। आप हिन्दी में बोल या टाइप कर सकते हैं। मैं कमरे, गैलरी, वीडियो और पूछताछ में मदद कर सकता हूँ।',ph:'Samara से पूछें…',rooms:'कमरे',gallery:'गैलरी',video:'वीडियो',enquiry:'पूछताछ',listen:'सुन रहा हूँ…',noVoice:'इस ब्राउज़र में वॉइस इनपुट उपलब्ध नहीं है। कृपया टाइप करें।',fallback:'मैं Samara Assisted Living, कमरे, गैलरी, वीडियो और पूछताछ के बारे में मदद कर सकता हूँ।'},
 kn:{name:'ಕನ್ನಡ',locale:'kn-IN',hello:'ನಮಸ್ಕಾರ! ನಾನು Samara AI. ನೀವು ಕನ್ನಡದಲ್ಲಿ ಮಾತನಾಡಬಹುದು ಅಥವಾ ಟೈಪ್ ಮಾಡಬಹುದು. ಕೊಠಡಿಗಳು, ಗ್ಯಾಲರಿ, ವೀಡಿಯೊ ಮತ್ತು ವಿಚಾರಣೆಗೆ ಸಹಾಯ ಮಾಡುತ್ತೇನೆ.',ph:'Samaraಗೆ ಕೇಳಿ…',rooms:'ಕೊಠಡಿಗಳು',gallery:'ಗ್ಯಾಲರಿ',video:'ವೀಡಿಯೊ',enquiry:'ವಿಚಾರಣೆ',listen:'ಕೇಳುತ್ತಿದ್ದೇನೆ…',noVoice:'ಈ ಬ್ರೌಸರ್‌ನಲ್ಲಿ ಧ್ವನಿ ಇನ್‌ಪುಟ್ ಲಭ್ಯವಿಲ್ಲ. ದಯವಿಟ್ಟು ಟೈಪ್ ಮಾಡಿ.',fallback:'Samara Assisted Living, ಕೊಠಡಿಗಳು, ಗ್ಯಾಲರಿ, ವೀಡಿಯೊ ಮತ್ತು ವಿಚಾರಣೆಯ ಬಗ್ಗೆ ನಾನು ಸಹಾಯ ಮಾಡಬಹುದು.'}
};
var lang='en', opened=false;
function esc(s){var d=document.createElement('div');d.textContent=s;return d.innerHTML}
function ui(){var root=document.createElement('div');root.innerHTML='<button class="sai-launch" id="sai-launch" aria-label="Ask Samara AI"><span>✦</span><span>Ask Samara AI</span></button><section class="sai-panel" id="sai-panel" aria-label="Samara AI assistant"><div class="sai-head"><img src="assets/samara-mark.png" alt=""><div class="sai-title"><strong>Samara AI</strong><small>Voice • Text • Rooms • Gallery</small></div><button class="sai-close" id="sai-close" aria-label="Close">×</button></div><div class="sai-langs" id="sai-langs"></div><div class="sai-msgs" id="sai-msgs" aria-live="polite"></div><div class="sai-quick" id="sai-quick"></div><form class="sai-compose" id="sai-form"><button type="button" class="sai-mic" id="sai-mic" aria-label="Voice input">🎙</button><input id="sai-input" autocomplete="off"><button class="sai-send" aria-label="Send">➤</button></form><div class="sai-note">Voice recognition availability depends on your browser/device.</div></section>';document.body.appendChild(root);renderLangs();setLang('en');bind()}
function add(text,who){var d=document.createElement('div');d.className='sai-msg '+(who==='user'?'sai-user':'sai-bot');d.textContent=text;document.getElementById('sai-msgs').appendChild(d);scroll()}
function media(src,cap,video){var d=document.createElement('div');d.className='sai-msg sai-media';d.innerHTML=video?'<video controls playsinline poster="assets/photos/video-poster.jpg"><source src="'+src+'" type="video/mp4"></video><p>'+esc(cap)+'</p>':'<img src="'+src+'" alt="'+esc(cap)+'" loading="lazy"><p>'+esc(cap)+'</p>';document.getElementById('sai-msgs').appendChild(d);scroll()}
function scroll(){var m=document.getElementById('sai-msgs');m.scrollTop=m.scrollHeight}
function renderLangs(){var x=document.getElementById('sai-langs');Object.keys(L).forEach(function(k){var b=document.createElement('button');b.className='sai-lang';b.type='button';b.dataset.lang=k;b.textContent=L[k].name;b.onclick=function(){setLang(k)};x.appendChild(b)})}
function setLang(k){lang=L[k]?k:'en';document.querySelectorAll('.sai-lang').forEach(function(b){b.classList.toggle('active',b.dataset.lang===lang)});document.getElementById('sai-input').placeholder=L[lang].ph;var q=document.getElementById('sai-quick');q.innerHTML='';[['rooms','rooms'],['gallery','gallery'],['video','video'],['enquiry','enquiry']].forEach(function(a){var b=document.createElement('button');b.type='button';b.textContent=L[lang][a[0]];b.onclick=function(){intent(a[1],true)};q.appendChild(b)});if(opened)add(L[lang].hello,'bot')}
function showRooms(){media('assets/photos/care-room-single.webp','Private / single care room');media('assets/photos/care-room.webp','Care room at Samara');media('assets/photos/care-room-triple.webp','Triple-sharing care room')}
function showGallery(){['centre-building','reception','welcome-wall','care-team','ribbon-cutting','lamp-lighting'].forEach(function(n){media('assets/photos/'+n+'.webp','Samara Assisted Living')})}
function intent(text,quick){var raw=String(text||''),s=raw.toLowerCase();if(!quick)add(raw,'user');
 if(s==='rooms'||/room|rooms|single|triple|அறை|ரூம்|గది|గదులు|कमरा|कमरे|ಕೊಠಡಿ|ರೂಮ್/.test(s)){showRooms();return}
 if(s==='gallery'||/gallery|photo|photos|picture|கேலரி|பட|గ్యాలరీ|ఫోటో|गैलरी|फोटो|ಗ್ಯಾಲರಿ|ಫೋಟೋ/.test(s)){showGallery();return}
 if(s==='video'||/video|reel|வீடியோ|వీడియో|वीडियो|ವೀಡಿಯೊ/.test(s)){media('assets/video/samara-opening.mp4','Samara Assisted Living — opening video',true);return}
 if(s==='enquiry'||/enquir|admission|contact|விசாரணை|அட்மிஷன்|చేర్పు|पूछताछ|प्रवेश|ವಿಚಾರಣೆ|ದಾಖಲಾತಿ/.test(s)){add(lang==='en'?'Certainly. I will take you to our care enquiry form.':L[lang].fallback,'bot');setTimeout(function(){location.href='contact.html#enquiry'},650);return}
 askAI(raw)}
function localReply(q){var s=String(q||'').toLowerCase();
 function say(x){return x[lang]||x.en}
 var R={
 who:{en:'Samara is suitable for elders who need daily support, people discharged from hospital who still need nursing care, people recovering after surgery, stroke, fractures or long illness, and families needing short-stay or respite care. We first assess the person’s health and care needs before admission.',ta:'தினசரி உதவி தேவைப்படும் முதியவர்கள், மருத்துவமனையிலிருந்து discharge ஆன பிறகும் nursing care தேவைப்படுபவர்கள், surgery, stroke, fracture அல்லது நீண்டநாள் நோய்க்குப் பிறகு மீண்டு வருபவர்கள், மற்றும் short-stay / respite care தேவைப்படுபவர்கள் Samara-வில் தங்கலாம். Admissionக்கு முன் உடல்நிலை மற்றும் care needs-ஐ மதிப்பீடு செய்கிறோம்.',te:'రోజువారీ సహాయం అవసరమైన వృద్ధులు, hospital discharge తర్వాత nursing care అవసరమైన వారు, surgery, stroke, fracture లేదా దీర్ఘకాల అనారోగ్యం తర్వాత కోలుకుంటున్న వారు, short-stay / respite care అవసరమైన వారు Samaraలో ఉండవచ్చు. Admissionకు ముందు health మరియు care needs‌ను పరిశీలిస్తాము.',hi:'Samara उन बुज़ुर्गों के लिए है जिन्हें रोज़मर्रा की सहायता चाहिए, hospital discharge के बाद nursing care चाहने वालों के लिए, surgery, stroke, fracture या लंबी बीमारी के बाद recovery करने वालों के लिए, और short-stay / respite care के लिए। Admission से पहले health और care needs का assessment किया जाता है।',kn:'ದೈನಂದಿನ ಸಹಾಯ ಬೇಕಿರುವ ಹಿರಿಯರು, hospital discharge ನಂತರ nursing care ಅಗತ್ಯವಿರುವವರು, surgery, stroke, fracture ಅಥವಾ ದೀರ್ಘಕಾಲದ ಅನಾರೋಗ್ಯದ ನಂತರ ಚೇತರಿಸಿಕೊಳ್ಳುವವರು ಹಾಗೂ short-stay / respite care ಬೇಕಿರುವವರು Samaraದಲ್ಲಿ ಉಳಿಯಬಹುದು. Admissionಗೆ ಮೊದಲು health ಮತ್ತು care needs ಪರಿಶೀಲಿಸಲಾಗುತ್ತದೆ.'},
 care:{en:'We provide 24×7 skilled nursing, medication management, regular vitals and doctor coordination, wound care and clinical procedures, physiotherapy and rehabilitation, diet support, and help with bathing, dressing, toileting, feeding and mobility. Care is planned around each resident.',ta:'24×7 skilled nursing, மருந்து மேலாண்மை, vitals மற்றும் doctor coordination, wound care, clinical procedures, physiotherapy & rehabilitation, diet support, மேலும் bathing, dressing, toileting, feeding மற்றும் mobility உதவி வழங்குகிறோம். ஒவ்வொரு resident-க்கும் அவர்களின் தேவைக்கேற்ப care plan செய்யப்படுகிறது.',te:'24×7 skilled nursing, medication management, vitals, doctor coordination, wound care, clinical procedures, physiotherapy & rehabilitation, diet support మరియు bathing, dressing, toileting, feeding, mobility సహాయం అందిస్తాము.',hi:'हम 24×7 skilled nursing, medication management, vitals, doctor coordination, wound care, clinical procedures, physiotherapy & rehabilitation, diet support तथा bathing, dressing, toileting, feeding और mobility में सहायता देते हैं।',kn:'ನಾವು 24×7 skilled nursing, medication management, vitals, doctor coordination, wound care, clinical procedures, physiotherapy & rehabilitation, diet support ಹಾಗೂ bathing, dressing, toileting, feeding ಮತ್ತು mobility ಸಹಾಯ ನೀಡುತ್ತೇವೆ.'},
 cost:{en:'Charges depend on the room type, length of stay and level of care required. Medicines, investigations and hospital expenses are generally separate unless included in a package. I do not want to quote an incorrect amount; please send an enquiry and our care team will confirm the current package and exact estimate.',ta:'கட்டணம் room type, தங்கும் காலம் மற்றும் தேவையான care level-ஐப் பொறுத்து மாறும். Medicines, investigations மற்றும் hospital expenses package-ல் சேர்க்கப்படாவிட்டால் பொதுவாக தனியாக bill செய்யப்படும். தவறான தொகையைச் சொல்ல விரும்பவில்லை; enquiry அனுப்பினால் தற்போதைய package மற்றும் சரியான estimate-ஐ care team உறுதிப்படுத்துவார்கள்.',te:'Charges room type, stay కాలం మరియు care level‌పై ఆధారపడి ఉంటాయి. Medicines, investigations మరియు hospital expenses packageలో లేకపోతే విడిగా bill చేస్తారు. తప్పు మొత్తం చెప్పకుండా, enquiry పంపితే current package మరియు exact estimate‌ను care team నిర్ధారిస్తుంది.',hi:'Charges room type, रहने की अवधि और care level पर निर्भर करते हैं। Medicines, investigations और hospital expenses package में शामिल न हों तो अलग bill होते हैं। सही current package और estimate के लिए enquiry भेजें; care team पुष्टि करेगी।',kn:'Charges room type, ಉಳಿಯುವ ಅವಧಿ ಮತ್ತು care level ಮೇಲೆ ಅವಲಂಬಿತವಾಗಿರುತ್ತವೆ. Medicines, investigations ಮತ್ತು hospital expenses packageನಲ್ಲಿ ಸೇರಿರದಿದ್ದರೆ ಪ್ರತ್ಯೇಕವಾಗಿ bill ಮಾಡಲಾಗುತ್ತದೆ. current package ಮತ್ತು exact estimateಗಾಗಿ enquiry ಕಳುಹಿಸಿ; care team ದೃಢಪಡಿಸುತ್ತದೆ.'},
 mobility:{en:'Yes. Samara provides mobility assistance, daily-living support and planned physiotherapy when appropriate. If the person cannot walk or is largely bed-bound, we first need to understand the medical condition, transfer, feeding and toileting needs, and the doctor’s advice so our care team can confirm the right support.',ta:'ஆம். Samara-வில் mobility assistance, தினசரி செயல்களுக்கு உதவி மற்றும் தேவைக்கேற்ப physiotherapy வழங்க முடியும். நடக்க முடியாதவர் அல்லது பெரும்பாலும் படுக்கையிலேயே இருப்பவர் என்றால், medical condition, transfer, feeding/toileting needs மற்றும் doctor advice-ஐ முதலில் தெரிந்துகொண்டு சரியான care level-ஐ எங்கள் குழு உறுதிப்படுத்தும்.',te:'అవును. Mobility assistance, daily-living support మరియు అవసరానికి అనుగుణంగా physiotherapy అందించవచ్చు. నడవలేని లేదా bed-bound వ్యక్తికి medical condition, transfer, feeding/toileting needs మరియు doctor advice తెలుసుకున్న తర్వాత care team సరైన support‌ను నిర్ధారిస్తుంది.',hi:'हाँ। Mobility assistance, daily-living support और आवश्यकता के अनुसार physiotherapy दी जा सकती है। जो व्यक्ति चल नहीं सकता या bed-bound है, उसके medical condition, transfer, feeding/toileting needs और doctor advice को समझकर care team सही support की पुष्टि करेगी।',kn:'ಹೌದು. Mobility assistance, daily-living support ಮತ್ತು ಅಗತ್ಯಕ್ಕೆ ಅನುಗುಣವಾಗಿ physiotherapy ನೀಡಬಹುದು. ನಡೆಯಲು ಆಗದ ಅಥವಾ bed-bound ವ್ಯಕ್ತಿಯ medical condition, transfer, feeding/toileting needs ಮತ್ತು doctor advice ತಿಳಿದು care team ಸರಿಯಾದ support ದೃಢಪಡಿಸುತ್ತದೆ.'},
 post:{en:'Yes. Post-hospital and step-down care is one of Samara’s core services. We support recovery after surgery, stroke, fractures or long illness with nursing, medication safety, monitoring, doctor coordination and planned physiotherapy.',ta:'ஆம். Post-hospital / step-down care Samara-வின் முக்கிய சேவைகளில் ஒன்று. Surgery, stroke, fracture அல்லது நீண்டநாள் நோய்க்குப் பிறகு nursing, medication safety, monitoring, doctor coordination மற்றும் planned physiotherapy மூலம் recovery-க்கு உதவுகிறோம்.',te:'అవును. Post-hospital / step-down care Samara ప్రధాన సేవల్లో ఒకటి. Surgery, stroke, fracture లేదా దీర్ఘకాల అనారోగ్యం తర్వాత nursing, medication safety, monitoring, doctor coordination మరియు physiotherapyతో recoveryకు సహాయం చేస్తాము.',hi:'हाँ। Post-hospital / step-down care Samara की मुख्य सेवाओं में से एक है। Surgery, stroke, fracture या लंबी बीमारी के बाद nursing, medication safety, monitoring, doctor coordination और physiotherapy के साथ recovery में सहायता दी जाती है।',kn:'ಹೌದು. Post-hospital / step-down care Samaraದ ಪ್ರಮುಖ ಸೇವೆಗಳಲ್ಲಿ ಒಂದು. Surgery, stroke, fracture ಅಥವಾ ದೀರ್ಘಕಾಲದ ಅನಾರೋಗ್ಯದ ನಂತರ nursing, medication safety, monitoring, doctor coordination ಮತ್ತು physiotherapy ಮೂಲಕ recoveryಗೆ ಸಹಾಯ ಮಾಡುತ್ತೇವೆ.'},
 admission:{en:'For admission, we first do a health assessment. Please keep recent medical records, current prescriptions, allergy information and the treating doctor’s details ready. We also encourage families to visit Samara before admission.',ta:'Admissionக்கு முதலில் health assessment செய்வோம். Recent medical records, current prescriptions, allergy information மற்றும் treating doctor details தயாராக வைத்திருக்கவும். Admissionக்கு முன் குடும்பத்தினர் Samara-வை நேரில் வந்து பார்க்கவும் பரிந்துரைக்கிறோம்.',te:'Admissionకు ముందు health assessment చేస్తాము. Recent medical records, current prescriptions, allergy information మరియు treating doctor details సిద్ధంగా ఉంచండి. Admissionకు ముందు కుటుంబం Samaraను సందర్శించాలని సూచిస్తాము.',hi:'Admission के लिए पहले health assessment किया जाता है। Recent medical records, current prescriptions, allergy information और treating doctor details तैयार रखें। Admission से पहले परिवार को Samara देखने के लिए भी प्रोत्साहित किया जाता है।',kn:'Admissionಗೆ ಮೊದಲು health assessment ಮಾಡಲಾಗುತ್ತದೆ. Recent medical records, current prescriptions, allergy information ಮತ್ತು treating doctor details ಸಿದ್ಧವಾಗಿರಲಿ. Admissionಗೆ ಮೊದಲು ಕುಟುಂಬ Samaraಗೆ ಭೇಟಿ ನೀಡುವುದನ್ನೂ ನಾವು ಪ್ರೋತ್ಸಾಹಿಸುತ್ತೇವೆ.'}
 };
 if(/hospital|ஹாஸ்பிடல்|மருத்துவமனை|ఆసుపత్రి|హాస్పిటల్|अस्पताल|हॉस्पिटल|ಆಸ್ಪತ್ರೆ|ಹಾಸ್ಪಿಟಲ್/.test(s))return say({en:'No. Samara is not a hospital. It is an assisted-living and supportive-care centre with trained nurses available 24×7, for people who need more than home care but do not need to remain in hospital. In an emergency, our nurses respond and arrange hospital transfer when needed. Would you like to see our rooms or know who can stay here?',ta:'இல்லை. Samara ஒரு ஹாஸ்பிடல் அல்ல. இது 24×7 பயிற்சி பெற்ற செவிலியர்கள் உள்ள Assisted Living மற்றும் supportive-care centre. வீட்டில் கிடைக்கும் பராமரிப்பை விட அதிக உதவி தேவைப்படுபவர்கள், ஆனால் மருத்துவமனையில் தொடர்ந்து தங்க வேண்டிய அவசியமில்லாதவர்களுக்காக இது அமைக்கப்பட்டுள்ளது. அவசரநிலையில் தேவையானால் மருத்துவமனைக்கு மாற்ற ஏற்பாடு செய்வோம். அறைகளைப் பார்க்க வேண்டுமா, அல்லது யார் இங்கு தங்கலாம் என்று தெரிந்துகொள்ள வேண்டுமா?',te:'కాదు. Samara హాస్పిటల్ కాదు. ఇది 24×7 trained nurses ఉన్న Assisted Living మరియు supportive-care centre. ఇంటి సంరక్షణకంటే ఎక్కువ సహాయం అవసరమైనా hospitalలో ఉండాల్సిన అవసరం లేని వారికి ఇది అనుకూలం.',hi:'नहीं। Samara अस्पताल नहीं है। यह 24×7 trained nurses वाला Assisted Living और supportive-care centre है, उन लोगों के लिए जिन्हें home care से अधिक सहायता चाहिए लेकिन hospital में रहने की आवश्यकता नहीं है।',kn:'ಇಲ್ಲ. Samara ಆಸ್ಪತ್ರೆಯಲ್ಲ. ಇದು 24×7 trained nurses ಇರುವ Assisted Living ಮತ್ತು supportive-care centre. ಮನೆಯ ಆರೈಕೆಯಿಗಿಂತ ಹೆಚ್ಚಿನ ಸಹಾಯ ಬೇಕಾದರೂ hospitalನಲ್ಲಿ ಉಳಿಯುವ ಅಗತ್ಯವಿಲ್ಲದವರಿಗೆ ಇದು ಸೂಕ್ತ.'});
 if(/who can stay|suitable|eligible|யார்.*(தங்க|சேர)|யாருக்கு|ఎవరు.*ఉండ|कौन.*रह|ಯಾರು.*ಉಳಿಯ/.test(s))return R.who;
 if(/what care|services|provide|என்ன.*(care|பராமரிப்பு|சேவை)|சேவைகள்|సేవ|देखभाल|सेवा|ಆರೈಕೆ|ಸೇವೆ/.test(s))return R.care;
 if(/how much|price|cost|charge|package|fees|rate|எவ்வளவு|கட்டணம்|விலை|பேக்கேஜ்|ధర|ఛార్జ|कितना|कीमत|शुल्क|पैकेज|ಎಷ್ಟು|ಬೆಲೆ|ಶುಲ್ಕ/.test(s))return R.cost;
 if(/cannot walk|can't walk|bedridden|wheelchair|mobility|நடக்க முடிய|படுக்கை|வீல்சேர்|నడవలే|व्हीलचेयर|चल नहीं|बिस्तर|ನಡೆಯಲು ಆಗ|ವೀಲ್/.test(s))return R.mobility;
 if(/after hospital|discharg|after surgery|stroke|fracture|டிஸ்சார்ஜ்|அறுவை|ஸ்ட்ரோக்|ఫ్రాక్చర్|डिस्चार्ज|सर्जरी|स्ट्रोक|ಡಿಸ್ಚಾರ್ಜ್|ಶಸ್ತ್ರಚಿಕಿತ್ಸೆ/.test(s))return R.post;
 if(/admission.*need|documents|what.*admission|அட்மிஷன்.*(என்ன|தேவை)|ஆவண|అడ్మిషన్|दाखिले|दस्तावेज|ದಾಖಲೆ/.test(s))return R.admission;
 if(/what is samara|about samara|சமரா.*(என்ன|பற்றி)|సమరా.*(ఏమి|గురించి)|समारा.*(क्या|बारे)|ಸಮಾರಾ.*(ಏನು|ಬಗ್ಗೆ)/.test(s))return say({en:'Samara Assisted Living is a residential care centre for elders and people who need assistance, supervision or continued support in daily life. It is designed as a place between hospital and home, with 24×7 nursing support.',ta:'Samara Assisted Living என்பது முதியவர்கள் மற்றும் தினசரி வாழ்க்கையில் உதவி, கண்காணிப்பு அல்லது தொடர்ச்சியான பராமரிப்பு தேவைப்படுபவர்களுக்கான residential care centre. Hospital மற்றும் home-க்கு இடைப்பட்ட பாதுகாப்பான care setting ஆக, 24×7 nursing support உடன் செயல்படுகிறது.',te:'Samara Assisted Living వృద్ధులు మరియు రోజువారీ సహాయం లేదా కొనసాగింపు care అవసరమైనవారికి residential care centre. Hospital మరియు home మధ్య 24×7 nursing supportతో care అందిస్తుంది.',hi:'Samara Assisted Living बुज़ुर्गों और रोज़मर्रा की सहायता या continued care की आवश्यकता वाले लोगों के लिए residential care centre है, जहाँ 24×7 nursing support उपलब्ध है।',kn:'Samara Assisted Living ಹಿರಿಯರು ಮತ್ತು ದೈನಂದಿನ ಸಹಾಯ ಅಥವಾ continued care ಅಗತ್ಯವಿರುವವರಿಗೆ residential care centre ಆಗಿದ್ದು, 24×7 nursing support ಲಭ್ಯವಿದೆ.'});
 return null}
function askAI(q){var local=localReply(q);if(local){add(local,'bot');return}if(!CFG.aiEndpoint){add(L[lang].fallback,'bot');return}fetch(CFG.aiEndpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:q,language:lang,page:location.pathname})}).then(function(r){if(!r.ok)throw 0;return r.json()}).then(function(x){add(x.reply||L[lang].fallback,'bot')}).catch(function(){add(L[lang].fallback,'bot')})}
function voice(){var SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){add(L[lang].noVoice,'bot');return}var r=new SR(),mic=document.getElementById('sai-mic');r.lang=L[lang].locale;r.interimResults=false;r.maxAlternatives=1;mic.classList.add('listening');mic.title=L[lang].listen;r.onresult=function(e){var t=e.results[0][0].transcript;document.getElementById('sai-input').value=t;intent(t,false)};r.onerror=function(){add(L[lang].noVoice,'bot')};r.onend=function(){mic.classList.remove('listening');mic.title=''};r.start()}
function bind(){var p=document.getElementById('sai-panel');document.getElementById('sai-launch').onclick=function(){p.classList.add('open');if(!opened){opened=true;add(L[lang].hello,'bot')}setTimeout(function(){document.getElementById('sai-input').focus()},50)};document.getElementById('sai-close').onclick=function(){p.classList.remove('open')};document.getElementById('sai-mic').onclick=voice;document.getElementById('sai-form').onsubmit=function(e){e.preventDefault();var i=document.getElementById('sai-input'),v=i.value.trim();if(v){i.value='';intent(v,false)}}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ui);else ui();
})();
