# -*- coding: utf-8 -*-
# All visible text: key -> (English, Tamil). Tamil should be reviewed by a native speaker.
T = {
# ---------- shared ----------
"nav.home": ("Home", "முகப்பு"),
"nav.about": ("About Us", "எங்களைப் பற்றி"),
"nav.services": ("Our Care", "எங்கள் சேவைகள்"),
"nav.careers": ("Careers", "வேலைவாய்ப்பு"),
"nav.contact": ("Contact", "தொடர்பு"),
"nav.enquire": ("Enquire Now", "விசாரிக்க"),
"brand.sub": ("Health Care LLP", "ஹெல்த் கேர் எல்எல்பி"),
"tagline": ("Compassion • Comfort • Dignity", "கருணை • ஆறுதல் • கண்ணியம்"),
"lang.switch": ("தமிழ்", "English"),
"lang.label": ("Switch to Tamil", "Switch to English"),
"menu.open": ("Menu", "மெனு"),
"cta.call": ("Call us", "அழைக்க"),
"cta.whatsapp": ("WhatsApp", "வாட்ஸ்அப்"),
"cta.enquire": ("Make an enquiry", "விசாரணை அனுப்ப"),
"cta.visit_sal": ("Visit Samara Assisted Living", "சமாரா அசிஸ்டட் லிவிங் இணையதளம்"),
"footer.about": ("Samara Health Care LLP builds and runs compassionate care services for elders and for people recovering after hospital.",
                 "முதியோருக்கும், மருத்துவமனையிலிருந்து திரும்பி குணமடைந்து வருபவர்களுக்கும் கருணையுடன் கூடிய பராமரிப்பு சேவைகளை சமாரா ஹெல்த் கேர் எல்எல்பி உருவாக்கி நடத்துகிறது."),
"footer.explore": ("Explore", "பக்கங்கள்"),
"footer.centre": ("Our centre", "எங்கள் மையம்"),
"footer.reach": ("Reach us", "தொடர்புக்கு"),
"footer.family": ("Family Portal", "குடும்பத்தினர் போர்டல்"),
"footer.staff": ("Staff Login", "பணியாளர் உள்நுழைவு"),
"footer.privacy": ("Privacy Notice", "தனியுரிமை அறிவிப்பு"),
"footer.rights": ("All rights reserved.", "அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை."),
"footer.emergency": ("In a medical emergency, call 108.", "மருத்துவ அவசரநிலையில் 108-ஐ அழைக்கவும்."),
"addr.line": ("Samara Assisted Living, Mogappair, Chennai – 600 037", "சமாரா அசிஸ்டட் லிவிங், முகப்பேர், சென்னை – 600 037"),

# ---------- home ----------
"home.title": ("Samara Health Care — Care that feels like family", "சமாரா ஹெல்த் கேர் — குடும்பம் போன்ற பராமரிப்பு"),
"home.kicker": ("Samara Health Care LLP", "சமாரா ஹெல்த் கேர் எல்எல்பி"),
"home.h1": ("Care that feels like family.", "குடும்பம் போல அக்கறையுடன் பராமரிப்பு."),
"home.lead": ("We build and run care services for elders and for people recovering after a hospital stay — safe, respectful and transparent. Our first centre, Samara Assisted Living, is now open in Mogappair, Chennai.",
              "முதியோருக்கும், மருத்துவமனை சிகிச்சைக்குப் பின் குணமடைந்து வருபவர்களுக்கும் பாதுகாப்பான, மரியாதையான, வெளிப்படையான பராமரிப்பு சேவைகளை நாங்கள் உருவாக்கி நடத்துகிறோம். எங்கள் முதல் மையமான சமாரா அசிஸ்டட் லிவிங், சென்னை முகப்பேரில் இப்போது செயல்பட்டு வருகிறது."),
"home.badge": ("Now open in Mogappair, Chennai", "சென்னை முகப்பேரில் இப்போது திறக்கப்பட்டுள்ளது"),
"home.stat1": ("24×7", "24×7"),
"home.stat1l": ("Nursing care", "செவிலியர் பராமரிப்பு"),
"home.stat2": ("3", "3"),
"home.stat2l": ("Room categories", "அறை வகைகள்"),
"home.stat3": ("1", "1"),
"home.stat3l": ("Integrated care team", "ஒருங்கிணைந்த பராமரிப்புக் குழு"),
"home.centre.k": ("Our first centre", "எங்கள் முதல் மையம்"),
"home.centre.h": ("Samara Assisted Living, Mogappair", "சமாரா அசிஸ்டட் லிவிங், முகப்பேர்"),
"home.centre.p": ("Professional post-hospital and step-down care, a safe transition from hospital to home. Inaugurated on 27 August 2026 by Dr. S. Manivannan, Founder & Managing Director, Kauvery Hospitals.",
                  "மருத்துவமனையிலிருந்து வீட்டிற்குப் பாதுகாப்பாகத் திரும்ப உதவும் தொழில்முறை மருத்துவமனைக்குப் பிந்தைய பராமரிப்பு. 27 ஆகஸ்ட் 2026 அன்று காவேரி மருத்துவமனைகளின் நிறுவனர் மற்றும் நிர்வாக இயக்குநர் டாக்டர் எஸ். மணிவண்ணன் அவர்களால் திறந்து வைக்கப்பட்டது."),
"home.centre.b1": ("24×7 skilled nursing care", "24×7 திறமையான செவிலியர் பராமரிப்பு"),
"home.centre.b2": ("Medication safety and doctor coordination", "பாதுகாப்பான மருந்து மேலாண்மை, மருத்துவர் ஒருங்கிணைப்பு"),
"home.centre.b3": ("Physiotherapy and rehabilitation", "பிசியோதெரபி மற்றும் மறுவாழ்வு"),
"home.centre.b4": ("Family Portal with daily updates", "தினசரி தகவல்களுடன் குடும்பத்தினர் போர்டல்"),
"home.values.k": ("What we stand for", "எங்கள் அடிப்படை"),
"home.values.h": ("Safe. Respectful. Reassuring.", "பாதுகாப்பு. மரியாதை. நம்பிக்கை."),
"home.v1.h": ("Compassion first", "முதலில் கருணை"),
"home.v1.p": ("Help with bathing, dressing, meals, toileting and mobility — always with patience and dignity.",
              "குளித்தல், உடை அணிதல், உணவு, கழிப்பறை, நடமாட்டம் — அனைத்திலும் பொறுமையுடனும் கண்ணியத்துடனும் உதவி."),
"home.v2.h": ("Clinical safety", "மருத்துவப் பாதுகாப்பு"),
"home.v2.p": ("Trained nurses round the clock, careful medication management, regular vitals and close coordination with doctors and hospitals.",
              "இரவு பகல் பயிற்சி பெற்ற செவிலியர்கள், கவனமான மருந்து மேலாண்மை, முறையான உடல்நிலை அளவீடுகள், மருத்துவர்கள் மற்றும் மருத்துவமனைகளுடன் நெருக்கமான ஒருங்கிணைப்பு."),
"home.v3.h": ("Transparency for families", "குடும்பத்தினருக்கு வெளிப்படைத்தன்மை"),
"home.v3.p": ("Digital care records, a secure Family Portal and clear, itemised billing — so families always know how their loved one is doing.",
              "டிஜிட்டல் பராமரிப்புப் பதிவுகள், பாதுகாப்பான குடும்பத்தினர் போர்டல், தெளிவான விரிவான கட்டண விவரம் — அன்புக்குரியவரின் நிலை குடும்பத்தினருக்கு எப்போதும் தெரியும்."),
"home.digital.k": ("Smart digital care", "ஸ்மார்ட் டிஜிட்டல் பராமரிப்பு"),
"home.digital.h": ("Care you can trust — with transparency built in.", "நம்பிக்கைக்குரிய பராமரிப்பு — வெளிப்படைத்தன்மையுடன்."),
"home.digital.p": ("Every care activity — medicines, vitals, meals, physiotherapy — is recorded digitally by our team. Authorised family members can follow their loved one's wellbeing securely from anywhere through the Family Portal.",
                   "மருந்துகள், உடல்நிலை அளவீடுகள், உணவு, பிசியோதெரபி — ஒவ்வொரு பராமரிப்புச் செயலும் எங்கள் குழுவால் டிஜிட்டலாகப் பதிவு செய்யப்படுகிறது. அங்கீகரிக்கப்பட்ட குடும்ப உறுப்பினர்கள் குடும்பத்தினர் போர்டல் மூலம் எங்கிருந்தும் பாதுகாப்பாகத் தெரிந்துகொள்ளலாம்."),
"home.digital.l1": ("Daily care updates", "தினசரி பராமரிப்புத் தகவல்கள்"),
"home.digital.l2": ("Medication and vitals summary", "மருந்து மற்றும் உடல்நிலை சுருக்கம்"),
"home.digital.l3": ("Physiotherapy progress", "பிசியோதெரபி முன்னேற்றம்"),
"home.digital.l4": ("Bills, receipts and documents", "கட்டணங்கள், ரசீதுகள், ஆவணங்கள்"),
"home.band.h": ("Looking for care for someone you love?", "உங்கள் அன்புக்குரியவருக்குப் பராமரிப்பு தேவையா?"),
"home.band.p": ("Talk to our care team. We will listen, explain the options and help you plan the next step.",
                "எங்கள் பராமரிப்புக் குழுவிடம் பேசுங்கள். உங்கள் தேவையைக் கேட்டு, வாய்ப்புகளை விளக்கி, அடுத்த படியைத் திட்டமிட உதவுவோம்."),

# ---------- about ----------
"about.title": ("About Us — Samara Health Care", "எங்களைப் பற்றி — சமாரா ஹெல்த் கேர்"),
"about.k": ("About us", "எங்களைப் பற்றி"),
"about.h1": ("A care company built around people, not just conditions.", "நோயை மட்டுமல்ல, மனிதரை மையமாகக் கொண்ட பராமரிப்பு நிறுவனம்."),
"about.lead": ("Samara Health Care LLP was established in 2026 to give elders and recovering patients a place between hospital and home — where medical care and compassionate living come together.",
               "மருத்துவமனைக்கும் வீட்டிற்கும் இடையே, மருத்துவப் பராமரிப்பும் கருணையான வாழ்க்கையும் இணையும் ஓர் இடத்தை முதியோருக்கும் குணமடைந்து வருபவர்களுக்கும் வழங்க 2026-இல் சமாரா ஹெல்த் கேர் எல்எல்பி தொடங்கப்பட்டது."),
"about.mission.h": ("Our mission", "எங்கள் நோக்கம்"),
"about.mission.p": ("To provide safe, respectful and reliable care that helps every resident live with comfort and dignity, and keeps families informed at every step.",
                    "ஒவ்வொரு குடியிருப்பாளரும் ஆறுதலுடனும் கண்ணியத்துடனும் வாழ உதவும் பாதுகாப்பான, மரியாதையான, நம்பகமான பராமரிப்பை வழங்குவதும், ஒவ்வொரு கட்டத்திலும் குடும்பத்தினருக்குத் தகவல் தருவதும்."),
"about.vision.h": ("Our vision", "எங்கள் தொலைநோக்கு"),
"about.vision.p": ("To be a trusted name in elder care and post-hospital recovery in Tamil Nadu, known for compassion, clinical safety and transparency.",
                   "கருணை, மருத்துவப் பாதுகாப்பு, வெளிப்படைத்தன்மை ஆகியவற்றுக்காக அறியப்படும், தமிழ்நாட்டில் முதியோர் பராமரிப்பு மற்றும் மருத்துவமனைக்குப் பிந்தைய மீட்பில் நம்பகமான பெயராக இருப்பது."),
"about.values.h": ("Our values", "எங்கள் மதிப்புகள்"),
"about.val1": ("Compassion — we treat every resident as family.", "கருணை — ஒவ்வொரு குடியிருப்பாளரையும் குடும்பமாகக் கருதுகிறோம்."),
"about.val2": ("Dignity — privacy, choice and respect in daily care.", "கண்ணியம் — அன்றாடப் பராமரிப்பில் தனியுரிமை, விருப்பம், மரியாதை."),
"about.val3": ("Safety — clinical standards and careful records.", "பாதுகாப்பு — மருத்துவத் தரநிலைகள், கவனமான பதிவுகள்."),
"about.val4": ("Honesty — clear communication and transparent billing.", "நேர்மை — தெளிவான தொடர்பு, வெளிப்படையான கட்டணம்."),
"about.lead.h": ("Leadership", "தலைமை"),
"about.dir": ("Director, Samara Health Care LLP", "இயக்குநர், சமாரா ஹெல்த் கேர் எல்எல்பி"),
"about.p1": ("Dr. Chella Boomi", "டாக்டர் செல்ல பூமி"),
"about.p2": ("Dr. Maneesha Boominathan", "டாக்டர் மனீஷா பூமிநாதன்"),
"about.time.h": ("Our journey", "எங்கள் பயணம்"),
"about.t1.d": ("2026", "2026"),
"about.t1.p": ("Samara Health Care LLP established.", "சமாரா ஹெல்த் கேர் எல்எல்பி தொடங்கப்பட்டது."),
"about.t2.d": ("27 August 2026", "27 ஆகஸ்ட் 2026"),
"about.t2.p": ("Samara Assisted Living, Mogappair, Chennai inaugurated by Dr. S. Manivannan, Founder & Managing Director, Kauvery Hospitals.",
               "சென்னை முகப்பேரில் சமாரா அசிஸ்டட் லிவிங், காவேரி மருத்துவமனைகளின் நிறுவனர் மற்றும் நிர்வாக இயக்குநர் டாக்டர் எஸ். மணிவண்ணன் அவர்களால் திறந்து வைக்கப்பட்டது."),
"about.t3.d": ("Today", "இன்று"),
"about.t3.p": ("Now open and serving residents.", "இப்போது செயல்பட்டு, குடியிருப்பாளர்களுக்குச் சேவை செய்து வருகிறது."),

# ---------- services ----------
"svc.title": ("Our Care — Samara Health Care", "எங்கள் சேவைகள் — சமாரா ஹெல்த் கேர்"),
"svc.k": ("Our care", "எங்கள் சேவைகள்"),
"svc.h1": ("When home care is no longer enough — but hospital care is not required.", "வீட்டுப் பராமரிப்பு போதாதபோது — ஆனால் மருத்துவமனை தேவையில்லாதபோது."),
"svc.lead": ("At Samara Assisted Living, a single integrated team of nurses, caregivers, physiotherapists and visiting doctors plans care around each person.",
             "சமாரா அசிஸ்டட் லிவிங்கில் செவிலியர்கள், பராமரிப்பாளர்கள், பிசியோதெரபிஸ்டுகள், வருகை தரும் மருத்துவர்கள் அடங்கிய ஒருங்கிணைந்த குழு ஒவ்வொருவருக்கும் ஏற்ற பராமரிப்பைத் திட்டமிடுகிறது."),
"svc.s1.h": ("24×7 skilled nursing", "24×7 திறமையான செவிலியர் பராமரிப்பு"),
"svc.s1.p": ("Round-the-clock trained nurses for monitoring, wound care, feeding support and clinical procedures.", "கண்காணிப்பு, காயப் பராமரிப்பு, உணவூட்டல் உதவி, மருத்துவ நடைமுறைகளுக்கு இரவு பகல் பயிற்சி பெற்ற செவிலியர்கள்."),
"svc.s2.h": ("Recovery after hospital", "மருத்துவமனைக்குப் பிந்தைய மீட்பு"),
"svc.s2.p": ("Step-down care after surgery, stroke, fractures or long illness — a safe bridge from hospital to home.", "அறுவை சிகிச்சை, பக்கவாதம், எலும்பு முறிவு அல்லது நீண்ட நோய்க்குப் பின் — மருத்துவமனையிலிருந்து வீட்டிற்குப் பாதுகாப்பான பாலம்."),
"svc.s3.h": ("Medication safety", "பாதுகாப்பான மருந்து மேலாண்மை"),
"svc.s3.p": ("Medicines given on time as prescribed, with every dose recorded and reviewed.", "மருத்துவர் பரிந்துரைத்தபடி சரியான நேரத்தில் மருந்துகள்; ஒவ்வொரு டோஸும் பதிவு செய்யப்பட்டு சரிபார்க்கப்படுகிறது."),
"svc.s4.h": ("Doctor coordination", "மருத்துவர் ஒருங்கிணைப்பு"),
"svc.s4.p": ("Regular vitals, doctor visits and coordination with the resident's own doctors and hospitals.", "முறையான உடல்நிலை அளவீடுகள், மருத்துவர் வருகைகள், குடியிருப்பாளரின் சொந்த மருத்துவர்கள் மற்றும் மருத்துவமனைகளுடன் ஒருங்கிணைப்பு."),
"svc.s5.h": ("Physiotherapy & rehabilitation", "பிசியோதெரபி மற்றும் மறுவாழ்வு"),
"svc.s5.p": ("Planned sessions to rebuild strength, balance and mobility, with progress shared with family.", "வலிமை, சமநிலை, நடமாட்டத்தை மீட்டெடுக்கத் திட்டமிட்ட அமர்வுகள்; முன்னேற்றம் குடும்பத்தினருடன் பகிரப்படும்."),
"svc.s6.h": ("Diet & nutrition", "உணவு மற்றும் ஊட்டச்சத்து"),
"svc.s6.p": ("Meals planned for each resident's health needs, with intake recorded daily.", "ஒவ்வொருவரின் உடல்நலத் தேவைக்கேற்ப திட்டமிட்ட உணவு; தினமும் உட்கொள்ளல் பதிவு."),
"svc.s7.h": ("Daily living & companionship", "அன்றாட உதவி மற்றும் துணை"),
"svc.s7.p": ("Gentle help with bathing, dressing, toileting and moving around, plus warm company every day.", "குளித்தல், உடை அணிதல், கழிப்பறை, நடமாட்டத்தில் மென்மையான உதவி; தினமும் அன்பான துணை."),
"svc.s8.h": ("Short stays & family respite", "குறுகிய தங்குதல் மற்றும் குடும்ப ஓய்வு"),
"svc.s8.p": ("Flexible stays when families travel, need a break, or are planning longer-term care.", "குடும்பத்தினர் பயணம் செல்லும்போது, ஓய்வு தேவைப்படும்போது அல்லது நீண்டகாலப் பராமரிப்பைத் திட்டமிடும்போது நெகிழ்வான தங்குதல்."),
"svc.who.h": ("Who may benefit", "யாருக்குப் பயன்படும்"),
"svc.who1": ("Elders living alone who need daily support", "அன்றாட உதவி தேவைப்படும், தனியாக வாழும் முதியோர்"),
"svc.who2": ("Patients discharged from hospital who still need nursing care", "மருத்துவமனையிலிருந்து வெளியேறியும் செவிலியர் பராமரிப்பு தேவைப்படுபவர்கள்"),
"svc.who3": ("People recovering from stroke, surgery or fractures", "பக்கவாதம், அறுவை சிகிச்சை, எலும்பு முறிவிலிருந்து மீண்டு வருபவர்கள்"),
"svc.who4": ("Families who need a safe short stay or respite", "பாதுகாப்பான குறுகிய தங்குதல் அல்லது ஓய்வு தேவைப்படும் குடும்பங்கள்"),
"svc.rooms.h": ("Comfortable living", "வசதியான தங்குமிடம்"),
"svc.rooms.p": ("Private, twin-sharing and triple-sharing rooms, with flexible package types. For current rooms and packages, please visit the Samara Assisted Living website or call us.",
                "தனி அறை, இருவர் பகிர்வு, மூவர் பகிர்வு அறைகள் மற்றும் நெகிழ்வான திட்டங்கள். தற்போதைய அறைகள் மற்றும் திட்டங்களுக்கு சமாரா அசிஸ்டட் லிவிங் இணையதளத்தைப் பார்க்கவும் அல்லது எங்களை அழைக்கவும்."),
"svc.rooms.cta": ("Rooms & packages", "அறைகள் மற்றும் திட்டங்கள்"),

# ---------- careers ----------
"car.title": ("Careers — Samara Health Care", "வேலைவாய்ப்பு — சமாரா ஹெல்த் கேர்"),
"car.k": ("Careers", "வேலைவாய்ப்பு"),
"car.h1": ("Build a career in compassionate care.", "கருணையான பராமரிப்பில் உங்கள் பணிவாழ்க்கையை அமையுங்கள்."),
"car.lead": ("We are looking for kind, skilled people who take pride in caring for others. Join a team that values training, teamwork and respect.",
             "பிறரைப் பராமரிப்பதில் பெருமை கொள்ளும், அன்பும் திறமையும் உள்ளவர்களை நாங்கள் தேடுகிறோம். பயிற்சி, குழுப்பணி, மரியாதையை மதிக்கும் குழுவில் இணையுங்கள்."),
"car.r1": ("Staff Nurses (GNM / B.Sc Nursing)", "ஸ்டாஃப் நர்ஸ் (GNM / B.Sc நர்சிங்)"),
"car.r2": ("Caregivers & Nursing Assistants", "பராமரிப்பாளர்கள் மற்றும் நர்சிங் உதவியாளர்கள்"),
"car.r3": ("Physiotherapists", "பிசியோதெரபிஸ்டுகள்"),
"car.r4": ("Housekeeping, kitchen & support staff", "தூய்மைப் பணி, சமையலறை மற்றும் உதவிப் பணியாளர்கள்"),
"car.why.h": ("Why work with us", "ஏன் எங்களுடன் பணியாற்ற வேண்டும்"),
"car.w1": ("Structured training and clear duties", "முறையான பயிற்சி, தெளிவான பணிகள்"),
"car.w2": ("Modern digital tools — less paperwork, more care", "நவீன டிஜிட்டல் கருவிகள் — குறைந்த காகிதப் பணி, அதிக பராமரிப்பு"),
"car.w3": ("A respectful, supportive team", "மரியாதையான, ஆதரவான குழு"),
"car.apply.h": ("How to apply", "விண்ணப்பிக்கும் முறை"),
"car.apply.p": ("Apply online on the Samara Assisted Living careers page, or send your name, qualification and experience on WhatsApp.",
                "சமாரா அசிஸ்டட் லிவிங் வேலைவாய்ப்புப் பக்கத்தில் ஆன்லைனில் விண்ணப்பிக்கவும், அல்லது உங்கள் பெயர், கல்வித் தகுதி, அனுபவத்தை வாட்ஸ்அப்பில் அனுப்பவும்."),
"car.apply.cta": ("Apply online", "ஆன்லைனில் விண்ணப்பிக்க"),

# ---------- contact ----------
"con.title": ("Contact & Enquiry — Samara Health Care", "தொடர்பு மற்றும் விசாரணை — சமாரா ஹெல்த் கேர்"),
"con.k": ("Contact us", "தொடர்பு கொள்ள"),
"con.h1": ("Tell us how we can help.", "நாங்கள் எப்படி உதவலாம் என்று சொல்லுங்கள்."),
"con.lead": ("Send an enquiry and our care team will call you back. For urgent admissions, please call us directly.",
             "விசாரணையை அனுப்புங்கள்; எங்கள் பராமரிப்புக் குழு உங்களைத் திரும்ப அழைக்கும். அவசர சேர்க்கைக்கு, நேரடியாக அழைக்கவும்."),
"con.form.h": ("Care enquiry", "பராமரிப்பு விசாரணை"),
"f.resident": ("Name of the person who needs care", "பராமரிப்பு தேவைப்படுபவரின் பெயர்"),
"f.age": ("Age (optional)", "வயது (விருப்பம்)"),
"f.contact": ("Your name", "உங்கள் பெயர்"),
"f.mobile": ("Your mobile number", "உங்கள் கைபேசி எண்"),
"f.mobile.hint": ("10-digit Indian mobile number", "10 இலக்க இந்திய கைபேசி எண்"),
"f.care": ("Care needed", "தேவைப்படும் பராமரிப்பு"),
"f.care.0": ("Please choose", "தேர்ந்தெடுக்கவும்"),
"f.care.1": ("Elderly care / assisted living", "முதியோர் பராமரிப்பு / அசிஸ்டட் லிவிங்"),
"f.care.2": ("Recovery after hospital discharge", "மருத்துவமனையிலிருந்து வெளியேறிய பின் மீட்பு"),
"f.care.3": ("Short stay / respite", "குறுகிய தங்குதல் / ஓய்வு"),
"f.care.4": ("Physiotherapy support", "பிசியோதெரபி உதவி"),
"f.care.5": ("Special / dedicated nurse", "தனி செவிலியர்"),
"f.care.6": ("Something else", "வேறு ஏதேனும்"),
"f.msg": ("Current condition or anything we should know (optional)", "தற்போதைய உடல்நிலை அல்லது நாங்கள் அறிய வேண்டியவை (விருப்பம்)"),
"f.consent": ("I agree that Samara may use these details to contact me about this enquiry, as described in the Privacy Notice.",
              "இந்த விசாரணை தொடர்பாக என்னைத் தொடர்பு கொள்ள, தனியுரிமை அறிவிப்பில் கூறியபடி, இந்த விவரங்களை சமாரா பயன்படுத்த ஒப்புக்கொள்கிறேன்."),
"f.send": ("Send enquiry", "விசாரணை அனுப்பு"),
"f.sending": ("Sending…", "அனுப்பப்படுகிறது…"),
"f.ok": ("Thank you. Your enquiry has reached our care team — we will call you soon.", "நன்றி. உங்கள் விசாரணை எங்கள் பராமரிப்புக் குழுவைச் சென்றடைந்தது — விரைவில் அழைப்போம்."),
"f.fail": ("Sorry, we could not send the form just now. Please send it on WhatsApp instead — your details are filled in for you.", "மன்னிக்கவும், இப்போது படிவத்தை அனுப்ப முடியவில்லை. பதிலாக வாட்ஸ்அப்பில் அனுப்பவும் — உங்கள் விவரங்கள் நிரப்பப்பட்டுள்ளன."),
"f.fail.cta": ("Send on WhatsApp", "வாட்ஸ்அப்பில் அனுப்பு"),
"f.err.name": ("Please enter a name (at least 2 letters).", "பெயரை உள்ளிடவும் (குறைந்தது 2 எழுத்துகள்)."),
"f.err.mobile": ("Please enter a valid 10-digit mobile number.", "சரியான 10 இலக்க கைபேசி எண்ணை உள்ளிடவும்."),
"f.err.care": ("Please choose the care needed.", "தேவைப்படும் பராமரிப்பைத் தேர்ந்தெடுக்கவும்."),
"f.err.consent": ("Please tick the consent box.", "ஒப்புதல் பெட்டியைத் தேர்வு செய்யவும்."),
"f.err.many": ("You have already sent a few enquiries. Our team will call you — or please call us directly.", "நீங்கள் ஏற்கனவே சில விசாரணைகளை அனுப்பியுள்ளீர்கள். எங்கள் குழு அழைக்கும் — அல்லது நேரடியாக அழைக்கவும்."),
"con.info.h": ("Reach us directly", "நேரடியாகத் தொடர்பு கொள்ள"),
"con.phone": ("Phone", "தொலைபேசி"),
"con.wa": ("WhatsApp", "வாட்ஸ்அப்"),
"con.addr": ("Address", "முகவரி"),
"con.map": ("Open in Google Maps", "கூகுள் மேப்ஸில் பார்க்க"),
"con.hours": ("Nursing care is available 24×7. For visits, please call ahead so we can welcome you.", "செவிலியர் பராமரிப்பு 24×7 கிடைக்கும். வருகைக்கு முன் அழைத்துத் தெரிவித்தால் உங்களை வரவேற்கத் தயாராக இருப்போம்."),

# ---------- privacy ----------
"pv.title": ("Privacy Notice — Samara Health Care", "தனியுரிமை அறிவிப்பு — சமாரா ஹெல்த் கேர்"),
"pv.k": ("Privacy notice", "தனியுரிமை அறிவிப்பு"),
"pv.h1": ("How we handle the details you share", "நீங்கள் பகிரும் விவரங்களை நாங்கள் கையாளும் முறை"),
"pv.p1": ("This notice explains how Samara Health Care LLP (\"Samara\", \"we\") uses the details you give us through this website, in line with India's Digital Personal Data Protection Act, 2023.",
          "இந்த இணையதளம் மூலம் நீங்கள் வழங்கும் விவரங்களை, இந்தியாவின் டிஜிட்டல் தனிநபர் தரவுப் பாதுகாப்புச் சட்டம், 2023-க்கு ஏற்ப, சமாரா ஹெல்த் கேர் எல்எல்பி எவ்வாறு பயன்படுத்துகிறது என்பதை இந்த அறிவிப்பு விளக்குகிறது."),
"pv.h.what": ("What we collect", "நாங்கள் சேகரிப்பவை"),
"pv.what": ("Only what you type into the enquiry form: the name and age of the person who needs care, your name, your mobile number, the type of care and any message you add.",
            "விசாரணைப் படிவத்தில் நீங்கள் உள்ளிடுவது மட்டும்: பராமரிப்பு தேவைப்படுபவரின் பெயர், வயது, உங்கள் பெயர், கைபேசி எண், பராமரிப்பு வகை, நீங்கள் சேர்க்கும் செய்தி."),
"pv.h.why": ("Why we use it", "ஏன் பயன்படுத்துகிறோம்"),
"pv.why": ("To contact you about your enquiry and to help plan care. We do not sell your details or use them for unrelated advertising.",
           "உங்கள் விசாரணை தொடர்பாகத் தொடர்பு கொள்ளவும், பராமரிப்பைத் திட்டமிட உதவவும் மட்டுமே. உங்கள் விவரங்களை விற்பதில்லை; தொடர்பில்லாத விளம்பரத்துக்குப் பயன்படுத்துவதில்லை."),
"pv.h.where": ("Where it is kept", "எங்கு வைக்கப்படுகிறது"),
"pv.where": ("In Samara's secure care management system. Only authorised Samara staff handling enquiries can see it.",
             "சமாராவின் பாதுகாப்பான பராமரிப்பு மேலாண்மை அமைப்பில். விசாரணைகளைக் கையாளும் அங்கீகரிக்கப்பட்ட சமாரா பணியாளர்கள் மட்டுமே பார்க்க முடியும்."),
"pv.h.keep": ("How long we keep it", "எவ்வளவு காலம் வைத்திருப்போம்"),
"pv.keep": ("Only as long as needed for your enquiry and any care that follows, or as required by law.",
            "உங்கள் விசாரணைக்கும் அதைத் தொடரும் பராமரிப்புக்கும் தேவையான காலம் வரை, அல்லது சட்டப்படி தேவைப்படும் வரை மட்டும்."),
"pv.h.rights": ("Your choices", "உங்கள் உரிமைகள்"),
"pv.rights": ("You may ask us to show, correct or delete your details, or withdraw your consent, at any time by calling or messaging us on the numbers on the Contact page.",
              "தொடர்பு பக்கத்தில் உள்ள எண்களில் அழைத்தோ செய்தி அனுப்பியோ, எப்போது வேண்டுமானாலும் உங்கள் விவரங்களைக் காட்டவோ, திருத்தவோ, நீக்கவோ, ஒப்புதலைத் திரும்பப் பெறவோ கேட்கலாம்."),
"pv.h.em": ("Not for emergencies", "அவசரநிலைக்கு அல்ல"),
"pv.em": ("This website is not monitored for emergencies. In a medical emergency, call 108.", "இந்த இணையதளம் அவசரநிலைகளுக்காகக் கண்காணிக்கப்படுவதில்லை. மருத்துவ அவசரநிலையில் 108-ஐ அழைக்கவும்."),
"pv.updated": ("Last updated: September 2026", "கடைசியாகப் புதுப்பிக்கப்பட்டது: செப்டம்பர் 2026"),

# ---------- 404 ----------
"nf.title": ("Page not found — Samara Health Care", "பக்கம் கிடைக்கவில்லை — சமாரா ஹெல்த் கேர்"),
"nf.h1": ("We couldn't find that page.", "அந்தப் பக்கம் கிடைக்கவில்லை."),
"nf.p": ("It may have moved. Please use the menu, or go back to the home page.", "அது இடம் மாறியிருக்கலாம். மெனுவைப் பயன்படுத்தவும், அல்லது முகப்புப் பக்கத்திற்குச் செல்லவும்."),
"nf.cta": ("Go to home page", "முகப்புப் பக்கம்"),
}
